"""alarms and counting tables

Revision ID: 3172e989e4e3
Revises: 
Create Date: 2026-10-01 14:47:45.304167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may reference sqlmodel types)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3172e989e4e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id', 'at'], unique=False)
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boxes')),
    sa.UniqueConstraint('base_url', name=op.f('uq_boxes_base_url'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_contacts_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('email', name=op.f('uq_contacts_email'))
    )
    op.create_table('alarm_rules',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('event_kinds', postgresql.ARRAY(sa.String(length=12)), nullable=False),
    sa.Column('match_mode', sa.String(length=10), nullable=False),
    sa.Column('min_match_score', sa.Float(), nullable=True),
    sa.Column('min_liveness', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('dedupe_scope', sa.String(length=8), nullable=False),
    sa.Column('max_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('email_delayed', sa.Boolean(), nullable=False),
    sa.Column('attach_snapshot', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dedupe_scope IN ('track', 'camera')", name=op.f('ck_alarm_rules_dedupe_scope')),
    sa.CheckConstraint("event_kinds <@ ARRAY['matched','stranger','face_capture','body_capture']::varchar[]", name=op.f('ck_alarm_rules_event_kinds_valid')),
    sa.CheckConstraint("match_mode IN ('anyone', 'strangers', 'known', 'targets')", name=op.f('ck_alarm_rules_match_mode')),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_alarm_rules_severity')),
    sa.CheckConstraint('cardinality(event_kinds) > 0', name=op.f('ck_alarm_rules_event_kinds_not_empty')),
    sa.CheckConstraint('cooldown_seconds >= 0', name=op.f('ck_alarm_rules_cooldown_seconds')),
    sa.CheckConstraint('max_delay_seconds >= 0', name=op.f('ck_alarm_rules_max_delay_seconds')),
    sa.CheckConstraint('min_liveness IS NULL OR min_liveness BETWEEN 0 AND 100', name=op.f('ck_alarm_rules_min_liveness')),
    sa.CheckConstraint('min_match_score IS NULL OR min_match_score BETWEEN 0 AND 100', name=op.f('ck_alarm_rules_min_match_score')),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_alarm_rules_box_id_boxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_alarm_rules_name'))
    )
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.SmallInteger(), nullable=True),
    sa.Column('count_enabled', sa.Boolean(), nullable=False),
    sa.Column('count_basis', sa.String(length=10), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("count_basis IN ('merged', 'face', 'body')", name=op.f('ck_cameras_count_basis')),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_cameras_box_id_boxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('box_id', 'device_id', name=op.f('uq_cameras_box_id_device_id'))
    )
    op.create_table('ingest_cursors',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=12), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overlap_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('events_ingested', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("stream IN ('recognition', 'capture')", name=op.f('ck_ingest_cursors_stream')),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_ingest_cursors_box_id_boxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('box_id', 'stream', name=op.f('pk_ingest_cursors'))
    )
    op.create_table('push_inbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed', 'ignored')", name=op.f('ck_push_inbox_status')),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_push_inbox_box_id_boxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_inbox'))
    )
    op.create_index('ix_push_inbox_pending', 'push_inbox', ['received_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('stranger_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.REAL()), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sighting_count', sa.Integer(), nullable=False),
    sa.Column('representative_image_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_stranger_profiles_box_id_boxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stranger_profiles'))
    )
    op.create_index('ix_stranger_profiles_seen', 'stranger_profiles', ['box_id', 'last_seen_at'], unique=False)
    op.create_table('alarm_rule_cameras',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_alarm_rule_cameras_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_alarm_rule_cameras_rule_id_alarm_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'camera_id', name=op.f('pk_alarm_rule_cameras'))
    )
    op.create_table('alarm_rule_recipients',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_alarm_rule_recipients_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_alarm_rule_recipients_rule_id_alarm_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'contact_id', name=op.f('pk_alarm_rule_recipients'))
    )
    op.create_table('alarm_rule_targets',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=6), nullable=False),
    sa.Column('target_value', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.CheckConstraint("target_type IN ('person', 'group')", name=op.f('ck_alarm_rule_targets_target_type')),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_alarm_rule_targets_rule_id_alarm_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'target_type', 'target_value', name=op.f('pk_alarm_rule_targets'))
    )
    op.create_table('alarm_rule_windows',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('iso_dow', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('iso_dow BETWEEN 1 AND 7', name=op.f('ck_alarm_rule_windows_iso_dow')),
    sa.CheckConstraint('start_time <> end_time', name=op.f('ck_alarm_rule_windows_not_empty')),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_alarm_rule_windows_rule_id_alarm_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_rule_windows'))
    )
    op.create_index('ix_alarm_rule_windows_rule', 'alarm_rule_windows', ['rule_id'], unique=False)
    op.create_table('count_buckets',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('local_hour', sa.SmallInteger(), nullable=False),
    sa.Column('local_minute', sa.SmallInteger(), nullable=False),
    sa.Column('iso_dow', sa.SmallInteger(), nullable=False),
    sa.Column('sightings', sa.Integer(), nullable=False),
    sa.Column('face_sightings', sa.Integer(), nullable=False),
    sa.Column('body_sightings', sa.Integer(), nullable=False),
    sa.Column('events', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('iso_dow BETWEEN 1 AND 7', name=op.f('ck_count_buckets_iso_dow')),
    sa.CheckConstraint('local_hour BETWEEN 0 AND 23', name=op.f('ck_count_buckets_local_hour')),
    sa.CheckConstraint('local_minute IN (0, 15, 30, 45)', name=op.f('ck_count_buckets_local_minute')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_count_buckets_camera_id_cameras')),
    sa.PrimaryKeyConstraint('camera_id', 'bucket_start', name=op.f('pk_count_buckets'))
    )
    op.create_index('ix_count_buckets_camera_day', 'count_buckets', ['camera_id', 'local_date', 'local_hour'], unique=False)
    op.create_index('ix_count_buckets_day', 'count_buckets', ['local_date'], unique=False)
    op.create_table('sightings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('local_hour', sa.SmallInteger(), nullable=False),
    sa.Column('iso_dow', sa.SmallInteger(), nullable=False),
    sa.Column('face_track_id', sa.BigInteger(), nullable=True),
    sa.Column('body_track_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('person_key', sa.String(length=100), nullable=False),
    sa.Column('person_source', sa.String(length=12), nullable=False),
    sa.Column('person_uuid', sa.String(length=64), nullable=True),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('stranger_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('best_match_score', sa.Float(), nullable=True),
    sa.Column('best_face_image_path', sa.Text(), nullable=True),
    sa.Column('best_body_image_path', sa.Text(), nullable=True),
    sa.Column('face_embedding', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.CheckConstraint("person_source IN ('recognized', 'stranger', 'unidentified')", name=op.f('ck_sightings_person_source')),
    sa.CheckConstraint('face_track_id IS NOT NULL OR body_track_id IS NOT NULL', name=op.f('ck_sightings_has_track')),
    sa.CheckConstraint('iso_dow BETWEEN 1 AND 7', name=op.f('ck_sightings_iso_dow')),
    sa.CheckConstraint('local_hour BETWEEN 0 AND 23', name=op.f('ck_sightings_local_hour')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_sightings_camera_id_cameras')),
    sa.ForeignKeyConstraint(['stranger_profile_id'], ['stranger_profiles.id'], name=op.f('fk_sightings_stranger_profile_id_stranger_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sightings'))
    )
    op.create_index('ix_sightings_camera_hour', 'sightings', ['camera_id', 'local_date', 'local_hour'], unique=False)
    op.create_index('ix_sightings_camera_time', 'sightings', ['camera_id', 'first_seen_at'], unique=False, postgresql_include=['person_key', 'person_source'])
    op.create_index('ix_sightings_person', 'sightings', ['camera_id', 'person_key', 'last_seen_at'], unique=False)
    op.create_index('ix_sightings_time', 'sightings', ['first_seen_at'], unique=False, postgresql_include=['person_key'])
    op.create_index('uq_sightings_body_track', 'sightings', ['camera_id', 'local_date', 'body_track_id'], unique=True, postgresql_where=sa.text('body_track_id IS NOT NULL'))
    op.create_index('uq_sightings_face_track', 'sightings', ['camera_id', 'local_date', 'face_track_id'], unique=True, postgresql_where=sa.text('face_track_id IS NOT NULL'))
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('face_track_id', sa.BigInteger(), nullable=True),
    sa.Column('body_track_id', sa.BigInteger(), nullable=True),
    sa.Column('sighting_id', sa.BigInteger(), nullable=True),
    sa.Column('person_uuid', sa.String(length=64), nullable=True),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('group_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('group_names', postgresql.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('face_image_path', sa.Text(), nullable=True),
    sa.Column('body_image_path', sa.Text(), nullable=True),
    sa.Column('panorama_path', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("kind IN ('matched', 'stranger', 'face_capture', 'body_capture')", name=op.f('ck_events_kind')),
    sa.CheckConstraint("source IN ('poll', 'push')", name=op.f('ck_events_source')),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], name=op.f('fk_events_box_id_boxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_events_camera_id_cameras')),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], name=op.f('fk_events_sighting_id_sightings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('box_id', 'kind', 'alarm_id', name=op.f('uq_events_box_id_kind_alarm_id'))
    )
    op.create_index('ix_events_camera_time', 'events', ['camera_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_occurred_brin', 'events', ['occurred_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_events_person_time', 'events', ['person_uuid', 'occurred_at'], unique=False, postgresql_where=sa.text('person_uuid IS NOT NULL'))
    op.create_index('ix_events_sighting', 'events', ['sighting_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('trigger_event_id', sa.BigInteger(), nullable=True),
    sa.Column('sighting_id', sa.BigInteger(), nullable=True),
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('person_uuid', sa.String(length=64), nullable=True),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('is_stranger', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('snapshot_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_incidents_severity')),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved', 'false_alarm')", name=op.f('ck_incidents_status')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_incidents_camera_id_cameras')),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_incidents_rule_id_alarm_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], name=op.f('fk_incidents_sighting_id_sightings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], name=op.f('fk_incidents_trigger_event_id_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('public_id', name=op.f('uq_incidents_public_id'))
    )
    op.create_index('ix_incidents_camera_time', 'incidents', ['camera_id', 'occurred_at'], unique=False)
    op.create_index('ix_incidents_rule_time', 'incidents', ['rule_id', 'occurred_at'], unique=False)
    op.create_index('ix_incidents_status_time', 'incidents', ['status', 'occurred_at'], unique=False)
    op.create_table('alarm_rule_state',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_incident_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_alarm_rule_state_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_incident_id'], ['incidents.id'], name=op.f('fk_alarm_rule_state_last_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], name=op.f('fk_alarm_rule_state_rule_id_alarm_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'camera_id', name=op.f('pk_alarm_rule_state'))
    )
    op.create_table('incident_events',
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_incident_events_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'event_id', name=op.f('pk_incident_events'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('to_address', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('email')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("status IN ('pending', 'sending', 'sent', 'failed', 'cancelled')", name=op.f('ck_notifications_status')),
    sa.CheckConstraint('attempts >= 0 AND attempts <= max_attempts', name=op.f('ck_notifications_attempts')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_notifications_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_notifications_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('incident_id', 'contact_id', 'channel', name=op.f('uq_notifications_incident_id_contact_id_channel'))
    )
    op.create_index('ix_notifications_due', 'notifications', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'sending')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_due', table_name='notifications', postgresql_where=sa.text("status IN ('pending', 'sending')"))
    op.drop_table('notifications')
    op.drop_table('incident_events')
    op.drop_table('alarm_rule_state')
    op.drop_index('ix_incidents_status_time', table_name='incidents')
    op.drop_index('ix_incidents_rule_time', table_name='incidents')
    op.drop_index('ix_incidents_camera_time', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_events_sighting', table_name='events')
    op.drop_index('ix_events_person_time', table_name='events', postgresql_where=sa.text('person_uuid IS NOT NULL'))
    op.drop_index('ix_events_occurred_brin', table_name='events', postgresql_using='brin')
    op.drop_index('ix_events_camera_time', table_name='events')
    op.drop_table('events')
    op.drop_index('uq_sightings_face_track', table_name='sightings', postgresql_where=sa.text('face_track_id IS NOT NULL'))
    op.drop_index('uq_sightings_body_track', table_name='sightings', postgresql_where=sa.text('body_track_id IS NOT NULL'))
    op.drop_index('ix_sightings_time', table_name='sightings', postgresql_include=['person_key'])
    op.drop_index('ix_sightings_person', table_name='sightings')
    op.drop_index('ix_sightings_camera_time', table_name='sightings', postgresql_include=['person_key', 'person_source'])
    op.drop_index('ix_sightings_camera_hour', table_name='sightings')
    op.drop_table('sightings')
    op.drop_index('ix_count_buckets_day', table_name='count_buckets')
    op.drop_index('ix_count_buckets_camera_day', table_name='count_buckets')
    op.drop_table('count_buckets')
    op.drop_index('ix_alarm_rule_windows_rule', table_name='alarm_rule_windows')
    op.drop_table('alarm_rule_windows')
    op.drop_table('alarm_rule_targets')
    op.drop_table('alarm_rule_recipients')
    op.drop_table('alarm_rule_cameras')
    op.drop_index('ix_stranger_profiles_seen', table_name='stranger_profiles')
    op.drop_table('stranger_profiles')
    op.drop_index('ix_push_inbox_pending', table_name='push_inbox', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('push_inbox')
    op.drop_table('ingest_cursors')
    op.drop_table('cameras')
    op.drop_table('alarm_rules')
    op.drop_table('contacts')
    op.drop_table('boxes')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
