[project]
name = "fastapi-app"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]",
    "httpx>=0.28.1",
    "opencv-python-headless>=5.0.0.93",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.47",
    "tzdata>=2026.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
